before:
  hooks:
    - ./set-version.sh

builds:
  - id: yor
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goarch: "386"
        goos: darwin
      - goarch: arm
        goos: windows

archives:
  - id: yor
    builds:
      - yor
    format_overrides:
      - goos: windows
        format: zip
